#!/bin/bash
# Smart Test Strategy - project-starter-guide
# Generated by create-qa-architect (Pro/Team/Enterprise feature)
# https://vibebuildlab.com/qa-architect
set -e

echo "🧠 Analyzing changes for optimal test strategy..."

# Environment variable overrides
if [[ "$SKIP_SMART" == "1" ]]; then
  echo "⚠️  SKIP_SMART=1 - Running comprehensive tests"
  npm run test:comprehensive
  exit 0
fi

if [[ "$FORCE_COMPREHENSIVE" == "1" ]]; then
  echo "🔴 FORCE_COMPREHENSIVE=1 - Running all tests"
  npm run test:comprehensive
  exit 0
fi

if [[ "$FORCE_MINIMAL" == "1" ]]; then
  echo "⚪ FORCE_MINIMAL=1 - Running lint only"
  npm run lint && npm run format:check
  exit 0
fi

# Collect metrics
CHANGED_FILES=$(git diff --name-only HEAD~1..HEAD 2>/dev/null | wc -l | tr -d ' ')
CHANGED_LINES=$(git diff --stat HEAD~1..HEAD 2>/dev/null | tail -1 | grep -o '[0-9]* insertions' | grep -o '[0-9]*' || echo "0")
CURRENT_BRANCH=$(git branch --show-current)
HOUR=$(date +%H)
DAY_OF_WEEK=$(date +%u)

# Project-specific high-risk patterns (customized per project type)
# Project type: Documentation
HIGH_RISK_FILES=$(git diff --name-only HEAD~1..HEAD 2>/dev/null | grep -E "guides/security|guides/deployment|setup-instructions" || true)
API_FILES=$(git diff --name-only HEAD~1..HEAD 2>/dev/null | grep -E "api/|routes/|endpoints/" || true)
CONFIG_FILES=$(git diff --name-only HEAD~1..HEAD 2>/dev/null | grep -E "(package\.json|\.env|config|tsconfig)" || true)
SECURITY_FILES=$(git diff --name-only HEAD~1..HEAD 2>/dev/null | grep -E "(auth|security|crypto|payment|billing)" || true)
TEST_FILES=$(git diff --name-only HEAD~1..HEAD 2>/dev/null | grep -E "test|spec|__tests__" || true)

# Calculate risk score (0-10)
RISK_SCORE=0

# File-based risk
[[ -n "$HIGH_RISK_FILES" ]] && RISK_SCORE=$((RISK_SCORE + 4))
[[ -n "$SECURITY_FILES" ]] && RISK_SCORE=$((RISK_SCORE + 3))
[[ -n "$API_FILES" ]] && RISK_SCORE=$((RISK_SCORE + 2))
[[ -n "$CONFIG_FILES" ]] && RISK_SCORE=$((RISK_SCORE + 2))

# Size-based risk
[[ $CHANGED_FILES -gt 10 ]] && RISK_SCORE=$((RISK_SCORE + 2))
[[ $CHANGED_FILES -gt 20 ]] && RISK_SCORE=$((RISK_SCORE + 3))
[[ $CHANGED_LINES -gt 200 ]] && RISK_SCORE=$((RISK_SCORE + 2))

# Branch-based risk
case $CURRENT_BRANCH in
  main|master|production) RISK_SCORE=$((RISK_SCORE + 3)) ;;
  hotfix/*) RISK_SCORE=$((RISK_SCORE + 4)) ;;
  release/*) RISK_SCORE=$((RISK_SCORE + 2)) ;;
  develop) RISK_SCORE=$((RISK_SCORE + 1)) ;;
esac

# Time pressure adjustment (strip leading zeros for arithmetic)
HOUR_NUM=$((10#$HOUR))
if [[ $HOUR_NUM -ge 9 && $HOUR_NUM -le 17 && $DAY_OF_WEEK -le 5 ]]; then
  echo "⏰ Work hours - Optimizing for speed"
  SPEED_BONUS=true
else
  SPEED_BONUS=false
fi

# Display analysis
echo ""
echo "📊 Analysis Results:"
echo "   📁 Files changed: $CHANGED_FILES"
echo "   📏 Lines changed: $CHANGED_LINES"
echo "   🌿 Branch: $CURRENT_BRANCH"
echo "   🎯 Risk Score: $RISK_SCORE/10"
echo "   ⚡ Speed Bonus: $SPEED_BONUS"
echo ""

# Test tier selection based on risk score
if [[ $RISK_SCORE -ge 7 ]]; then
  echo "🔴 HIGH RISK - Comprehensive validation"
  echo "   • All tests + security audit"
  # Runs: npm run test:comprehensive 2>/dev/null || (npm run lint && npm run link:check 2>/dev/null)
  npm run test:comprehensive 2>/dev/null || (npm run lint && npm run link:check 2>/dev/null)
elif [[ $RISK_SCORE -ge 4 ]]; then
  echo "🟡 MEDIUM RISK - Standard validation"
  echo "   • Fast tests + integration (excludes slow tests)"
  # Runs: npm run test:medium 2>/dev/null || npm run lint && npm run spell:check 2>/dev/null
  npm run test:medium 2>/dev/null || npm run lint && npm run spell:check 2>/dev/null
elif [[ $RISK_SCORE -ge 2 || "$SPEED_BONUS" == "false" ]]; then
  echo "🟢 LOW RISK - Fast validation"
  echo "   • Unit tests only"
  # Runs: npm run test:fast 2>/dev/null || npm run lint
  npm run test:fast 2>/dev/null || npm run lint
else
  echo "⚪ MINIMAL RISK - Quality checks only"
  echo "   • Lint + format check"
  # Runs: npm run lint 2>/dev/null || npx markdownlint "**/*.md"
  npm run lint 2>/dev/null || npx markdownlint "**/*.md"
fi

echo ""
echo "💡 Tip: Run 'npm run test:comprehensive' locally for full validation"
echo "💎 Smart Test Strategy powered by QA Architect Pro"
